on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
      
      - name: Copy .env.example to .env
        run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${1%.*}"' _ {} \;
      
      # Run typecheck and lint in separate steps
      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
